#!/usr/bin/env bash

function run_task {
  task=$@

  ${task}
  local_run_task_result=$?

  if [ "${local_run_task_result}" != "0" ]; then
    echo "Task has failed with exit code ${local_run_task_result}" 1>&2
    echo "${task}" 1>&2
    exit ${local_run_task_result}
  fi
}


export -f run_task
